#!/bin/bash

# Compilation des classes + exceptions
javac -classpath ./classes -sourcepath ./src -d ./classes $(find ./src -name *.java)

# Compilation des tests
javac -classpath ./classestest:/usr/share/java/junit4-4.12.jar:/usr/share/java/hamcrest-library-1.3.jar:./classes -sourcepath ./srctest -d ./classestest $(find ./srctest -name *.java)

if [ "$1" = "+" ]
then
  javadoc -d javadoc -sourcepath src -subpackages fr
fi

if [ "$1" = "x" ]
then
  java -classpath classes fr.insarouen.asi.prog.MainTest
fi

if [ "$1" = "t" ]
then
  java -classpath ./classestest:/usr/share/java/junit4-4.12.jar:/usr/share/java/hamcrest-library-1.3.jar:./classes org.junit.runner.JUnitCore fr.insarouen.asi.prog.AllTests

fi
